# Generated by Django 4.1.2 on 2022-11-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_url', models.URLField()),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('fax', models.CharField(blank=True, max_length=200, null=True)),
                ('copyright_text', models.TextField()),
            ],
        ),
    ]
