# Generated by Django 4.1.2 on 2022-11-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
